// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLw_f_WyQBaIfnA18s81MbRumTYJDM1cQ',
    appId: '1:777720306386:web:004ffed3b74e0077272b0b',
    messagingSenderId: '777720306386',
    projectId: 'findyourteam-4e66c',
    authDomain: 'findyourteam-4e66c.firebaseapp.com',
    storageBucket: 'findyourteam-4e66c.firebasestorage.app',
    measurementId: 'G-DWHWNXQV20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiCtxG6Gzw6m78FWv1ZVOa5fF3TCtcsTQ',
    appId: '1:777720306386:android:b5154c75f87fdf9b272b0b',
    messagingSenderId: '777720306386',
    projectId: 'findyourteam-4e66c',
    storageBucket: 'findyourteam-4e66c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkLiw4x5np1mBpozFT0nPGZYw4BUFnJsg',
    appId: '1:777720306386:ios:900a3db06b6cfbdf272b0b',
    messagingSenderId: '777720306386',
    projectId: 'findyourteam-4e66c',
    storageBucket: 'findyourteam-4e66c.firebasestorage.app',
    iosBundleId: 'com.example.findYourTeam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkLiw4x5np1mBpozFT0nPGZYw4BUFnJsg',
    appId: '1:777720306386:ios:900a3db06b6cfbdf272b0b',
    messagingSenderId: '777720306386',
    projectId: 'findyourteam-4e66c',
    storageBucket: 'findyourteam-4e66c.firebasestorage.app',
    iosBundleId: 'com.example.findYourTeam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLw_f_WyQBaIfnA18s81MbRumTYJDM1cQ',
    appId: '1:777720306386:web:fe3dfe58f5cf9fdd272b0b',
    messagingSenderId: '777720306386',
    projectId: 'findyourteam-4e66c',
    authDomain: 'findyourteam-4e66c.firebaseapp.com',
    storageBucket: 'findyourteam-4e66c.firebasestorage.app',
    measurementId: 'G-8EKX0DWS25',
  );
}
